Fixing classes to resemble UML
HenriqueSabino/Ip2Project pull request #14
Opened 2020-10-01 21:22 UTC by HenriqueSabino

2020-10-01 22:55 UTC, HyanBatista requested changes

2020-10-01 22:55 UTC, HyanBatista commented on src/main/java/models/Administrator.java
> +    this.registerId = registerID;
Ficou com o ID maiúsculo. Se foi proposital, então não precisa usar o this em registerId, porque o java já iria considerar com duas variáveis diferentes.

2020-10-01 22:55 UTC, HyanBatista commented on src/main/java/models/Administrator.java
> +  public int getRegisterId() {
Na UML este método está escrito de forma diferente.

2020-10-01 22:55 UTC, HyanBatista commented on src/main/java/models/CartItem.java
>      this.product = product;
Na nova UML este método está retornando um produto.

2020-10-01 22:55 UTC, HyanBatista commented on src/main/java/models/CureReport.java
>    }
Acredito que esteja faltando o método getCures.

2020-10-01 22:55 UTC, HyanBatista commented on src/main/java/models/Nurse.java
> +    this.registerId = registerID;
Case sensitive. O uso do this é desnecessário.

2020-10-01 22:55 UTC, HyanBatista commented on src/main/java/models/Nurse.java
> +  public int getRegisterId() {
Na UML este método está escrito de maneira diferente.

2020-10-01 22:55 UTC, HyanBatista commented on src/main/java/models/Order.java
> +  public int getId() {
Na UML este método tem uma nomenclatura diferente.

2020-10-01 22:55 UTC, HyanBatista commented on src/main/java/models/SalesClerk.java
> +    this.registerId = registerID;
* a palavra chave this é desnecessária

2020-10-01 22:55 UTC, HyanBatista commented on src/main/java/models/Trainer.java
> +    this.registerId = registerID;
* o this é desnecessário.

2020-10-01 23:15 UTC, HyanBatista approved these changes

2020-10-02 05:32 UTC, S1lasAugusto approved these changes

2020-10-02 13:39 UTC, NelsuLins approved these changes

2020-10-02 13:44 UTC, merged