Implementing CureDao and Minor Changes in the Cure.java
HenriqueSabino/Ip2Project pull request #16
Opened 2020-10-08 19:16 UTC by NelsuLins

2020-10-08 19:43 UTC, HenriqueSabino requested changes

2020-10-08 19:43 UTC, HenriqueSabino commented on src/main/java/models/Cure.java
> +      Trainer client) {
Tá faltando uma linha em branco entre a linha da chave dos construtores e o código dos construtores em si

2020-10-08 19:43 UTC, HenriqueSabino commented on src/main/java/models/dao/impl/CureDaoFiles.java
> +      Trainer ash = new Trainer("Ash", "Pallet", "male", "ash", "password", "email");
Esses códigos aqui no construtor só devem existir caso for uma informação que tem que ser criada na inicialização do projeto, tipo o login do admin. Essas informações que tu colocou aqui são de teste então deveriam estar no main

2020-10-08 19:43 UTC, HenriqueSabino commented on src/main/java/models/dao/impl/CureDaoFiles.java
> +    if (dao.findAll().size() == 1) {
Essa verificação pode verificar se a lista está vazia, pq nenhuma informação vai ser gerada na inicialização

2020-10-08 20:04 UTC, HenriqueSabino requested changes

2020-10-08 20:04 UTC, HenriqueSabino commented on src/main/java/models/dao/impl/CureDaoFiles.java
> +    if (file.exists()) {
Se não existe faz o que?

2020-10-08 20:13 UTC, HenriqueSabino approved these changes

2020-10-09 14:27 UTC, S1lasAugusto approved these changes

2020-10-09 17:06 UTC, HyanBatista approved these changes

2020-10-09 17:06 UTC, merged