Hyanbatista sprint 02
HenriqueSabino/Ip2Project pull request #18
Opened 2020-10-09 19:11 UTC by HyanBatista

Order DAO implementation and CureReport class update.

2020-10-09 19:45 UTC, S1lasAugusto commented on src/main/java/models/dao/impl/OrderDaoFiles.java
> +    // Please, backup and delete localStorage\\users.ser before testin
juro que só achei esse comentário aqui fora de lugar que seria outra coisa nesse users.ser ai

2020-10-09 20:07 UTC, HenriqueSabino requested changes

2020-10-09 20:07 UTC, HenriqueSabino commented on src/main/java/models/CureReport.java
> +  public CureReport(LocalDateTime startDate, LocalDateTime endDate, Trainer client, User employee) {
Senti falta de um construtor com data de início e fim e só o funcionário pra poder ter um filtragem de curas feitas por cada funcionário

2020-10-09 20:07 UTC, HenriqueSabino commented on src/main/java/models/CureReport.java
> +  public CureReport(LocalDateTime startDate, LocalDateTime endDate, Trainer client, User employee) {
Senti falta também de ter construtores que não precisem de um intervalo específico de datas, então talvez seja mais interessante um construtor padrão pra essa classe que não obrigue que nenhum dos atributos sejam preenchido, e caso nenhum seja retornar a lista com todas as curas tlgd

2020-10-09 20:07 UTC, HenriqueSabino commented on src/main/java/models/CureReport.java
> +    if (employee == null && client == null) {
Pra facilitar tua vida tu pode fazer assim:

```java
if (employee != null) {
  // filtrar os funcionários
}

if (client != null) {
  // filtrar por clientes
}

if (startDate != null) {
  // filtrar curas depois da data
}

// etc
```

2020-10-09 20:07 UTC, HenriqueSabino commented on src/main/java/models/ShoppingCart.java
> +            "cartItemList=" + cartItemList +
Dúvida, `cartItemList.toString()` tem alguma visualização bonitinha?

2020-10-09 20:07 UTC, HenriqueSabino commented on src/main/java/models/dao/impl/OrderDaoFiles.java
> +      orders.add(new Order(null, null, null));
Não precisa adicionar um pedido pra salvar a lista, pode salvar uma lista vazia mesmo

2020-10-09 20:07 UTC, HenriqueSabino commented on src/main/java/models/dao/impl/OrderDaoFiles.java
> +    // Please, backup and delete localStorage\\users.ser before testin
Também acho, tem que renomear isso aí

2020-10-09 20:07 UTC, HenriqueSabino commented on src/main/java/models/dao/impl/OrderDaoFiles.java
> +      Nurse joy = new Nurse(
Acho que só pra fins de coesão de projeto ao invés de `Nurse` o funcionário deveria ser um vendedor

2020-10-09 23:02 UTC, HenriqueSabino approved these changes

2020-10-09 23:10 UTC, NelsuLins approved these changes

2020-10-10 00:04 UTC, HenriqueSabino requested changes

2020-10-10 00:04 UTC, HenriqueSabino commented on src/main/java/models/CureReport.java
> +          cures.add(c);
Mudar a condicional para o inverso e remover elementos ao invés de adicionar
```java
    List<Cure> allCures = getAllCures();
    List<Cure> cures = new ArrayList<>();
    cures.addAll(allCures);

    if (employee != null) {

      for (Cure c : allCures) {

        if (!employee.getUsername().equals(c.getEmployee().getUsername())) {

          cures.remove(c);
```

2020-10-11 00:13 UTC, S1lasAugusto approved these changes

2020-10-11 00:15 UTC, HenriqueSabino approved these changes

2020-10-11 06:00 UTC, merged