Implementing ProductDao and MinorChanges in the product
HenriqueSabino/Ip2Project pull request #19
Opened 2020-10-11 07:42 UTC by S1lasAugusto

2020-10-11 11:30 UTC, HenriqueSabino requested changes

2020-10-11 11:30 UTC, HenriqueSabino commented on src/main/java/models/dao/impl/ProductDaoFiles.java
> +      } catch (NameOrDescriptionInProductException e) {
Nomenclatura deveria ser `NameOrDescriptionInUseException`

2020-10-11 11:30 UTC, HenriqueSabino commented on src/main/java/models/Product.java
> +  public void setRegisterId(int id) {
Nomeclatura deveria ser `setId`

2020-10-12 01:16 UTC, HenriqueSabino requested changes

2020-10-12 01:16 UTC, HenriqueSabino commented on src/main/java/models/dao/impl/exception/NameOrDescriptionInUserException.java
> +  public NameOrDescriptionInUserException(String message) {
`NameOrDescriptionInUseException`* não `InUser`

2020-10-12 01:51 UTC, HenriqueSabino approved these changes

2020-10-12 20:42 UTC, HyanBatista approved these changes

2020-10-12 21:36 UTC, NelsuLins approved these changes

2020-10-12 21:36 UTC, merged