Implementing Pokemon and User models
HenriqueSabino/Ip2Project pull request #6
Opened 2020-09-11 02:58 UTC by NelsuLins

It contains the initial implementations of Pokemon and User models

2020-09-11 12:10 UTC, HenriqueSabino commented on src/main/java/models/User.java
A identação nesse arquivo tá errada, por algum motivo só nele o espaçamento das propriedades e métodos tão de 1 espaço, quando era pra ser de 2 espaços.
```java
public abstract class User extends Person {
  private String username;
  ...
}
```

2020-09-11 12:11 UTC, HenriqueSabino requested changes
No arquivo `User` tem lá comentado o que é pra ser alterado

2020-09-12 01:33 UTC, HenriqueSabino approved these changes

2020-09-12 01:36 UTC, S1lasAugusto approved these changes

2020-09-12 01:53 UTC, HyanBatista requested changes

2020-09-12 01:53 UTC, HyanBatista commented on src/main/java/models/PokemonType.java
> +  WATER,
É nesse modelo, sem vírgula no final: 
`enum Level {
  LOW,
  MEDIUM,
  HIGH
}`

2020-09-12 02:30 UTC, HenriqueSabino approved these changes

2020-09-12 13:34 UTC, HyanBatista approved these changes

2020-09-12 13:34 UTC, merged