Adding Order
HenriqueSabino/Ip2Project pull request #8
Opened 2020-09-14 01:07 UTC by S1lasAugusto

### Acharam, que eu estava derrotado
Quem achou estava errado,
Eu voltei, to aqui, se liga só, escuta aí.

2020-09-14 01:12 UTC, HenriqueSabino approved these changes

2020-09-14 22:54 UTC, HyanBatista requested changes

2020-09-14 22:54 UTC, HyanBatista commented on src/main/java/models/Order.java
> +  public Order(int id, ShoppingCart shoppingCart, SalesClerk salesClerk, Trainer client) {
Como vão existir 0 ou 1 sales clerk, seria interessante criar dois construtores.
`public Order(int id, ShoppingCart shoppingCart, SalesClerk salesClerk, Trainer client)`
e
`public Order(int id, ShoppingCart shoppingCart, Trainer client)`

2020-09-14 22:54 UTC, HyanBatista commented on src/main/java/models/Order.java
> +    this.orderDate = new Date();
Talvez seja bom a gente tentar aplicar a Java Data Time API logo no começo do projeto.
[https://www.journaldev.com/2800/java-8-date-localdate-localdatetime-instant#:~:text=LocalDate%20is%20an%20immutable%20class,date%20to%20create%20LocalDate%20instance.](url)

2020-09-14 23:09 UTC, HenriqueSabino commented on src/main/java/models/Order.java
> +  public Order(int id, ShoppingCart shoppingCart, SalesClerk salesClerk, Trainer client) {
Eita, vdd tinha esquecido desse ponto

2020-09-15 02:09 UTC, HenriqueSabino approved these changes

2020-09-16 16:26 UTC, NelsuLins approved these changes

2020-09-16 18:58 UTC, HyanBatista approved these changes

2020-09-16 18:58 UTC, merged